name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy repository via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: 102.37.220.75
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/azureuser/repo"  # Copy the entire repository to this directory on the VM

    - name: Execute commands via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 102.37.220.75
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/azureuser/repo
          docker-compose down
          docker-compose up -d
