name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 74.225.176.128 >> ~/.ssh/known_hosts

      - name: Connect to VM and manage repository
        run: |
          ssh -i ~/.ssh/id_rsa -o HostKeyAlgorithms=+ssh-rsa testadmin@74.225.176.128 << 'EOF'
            echo 'Connected to Azure VM'
            # Create a directory for the repo if it doesn't exist
            REPO_DIR=~/repo
            if [ ! -d "$REPO_DIR" ]; then
              echo "Cloning the repository..."
              git clone https://github.com/BENZ199/compose_for_reactnodejsmysqlwithadminer.git "$REPO_DIR"
            else
              echo "Repository already exists. Pulling the latest changes..."
              cd "$REPO_DIR"
              git pull origin main  # Change 'main' if your branch name is different
            fi
          EOF
