name: Connect to Azure VM

on:
  push:
    branches:
      - main

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 102.37.221.106 >> ~/.ssh/known_hosts

      - name: Connect to VM
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@102.37.221.106 "echo 'Connected to Azure VM'"
